//
// Created by Maxwell on 2021-02-12.
//

#ifndef VALKYRIE_SRC_WIN32_FUNCTIONS_HPP
#define VALKYRIE_SRC_WIN32_FUNCTIONS_HPP

#include "DynamicLoader.hpp"

#ifndef VALKYRIE_KERNEL_LIBRARY
#define VALKYRIE_KERNEL_LIBRARY "KernelBase.dll"
#endif
#ifndef VALKYRIE_DEBUG_HELP_LIBRARY
#define VALKYRIE_DEBUG_HELP_LIBRARY "DbgHelp.dll"
#endif


#include <DbgHelp.h>
#include <Psapi.h>


namespace valkyrie{

  namespace {
    class DebugApi{
      DynamicLoader debugHelpLib{VALKYRIE_DEBUG_HELP_LIBRARY};
    public:
      /* Debug Help */
      VK_foreach(VK_bind_front(VK_load_function, debugHelpLib),
                 EnumDirTree,
                 EnumerateLoadedModules,
                 EnumerateLoadedModulesEx,
                 FindDebugInfoFile,
                 FindDebugInfoFileEx,
                 FindExecutableImage,
                 FindExecutableImageEx,
                 GetSymLoadError,
                 GetTimestampForLoadedLibrary,
                 ImageDirectoryEntryToData,
                 ImageDirectoryEntryToDataEx,
                 ImagehlpApiVersion,
                 ImagehlpApiVersionEx,
                 ImageNtHeader,
                 ImageRvaToSection,
                 ImageRvaToVa,
                 MakeSureDirectoryPathExists,
                 SearchTreeForFile,
                 SetSymLoadError,
                 StackWalk,
                 StackWalkEx,
                 SymAddrIncludeInlineTrace,
                 SymAddSourceStream,
                 SymAddSymbol,
                 SymCleanup,
                 SymCompareInlineTrace,
                 SymDeleteSymbol,
                 SymEnumerateModules,
                 SymEnumLines,
                 SymEnumProcesses,
                 SymEnumSourceFiles,
                 SymEnumSourceFileTokens,
                 SymEnumSourceLines,
                 SymEnumSymbols,
                 SymEnumSymbolsEx,
                 SymEnumSymbolsForAddr,
                 SymEnumTypes,
                 SymEnumTypesByName,
                 SymFindDebugInfoFile,
                 SymFindExecutableImage,
                 SymFindFileInPath,
                 SymFromAddr,
                 SymFromIndex,
                 SymFromInlineContext,
                 SymFromName,
                 SymFromToken,
                 SymFunctionTableAccess,
                 SymFunctionTableAccess64AccessRoutines,
                 SymGetExtendedOption,
                 SymGetFileLineOffsets64,
                 SymGetHomeDirectory,
                 SymGetLineFromAddr,
                 SymGetLineFromInlineContext,
                 SymGetLineFromName,
                 SymGetLineNext,
                 SymGetLinePrev,
                 SymGetModuleBase,
                 SymGetModuleInfo,
                 SymGetOmaps,
                 SymGetOptions,
                 SymGetScope,
                 SymGetSearchPath,
                 SymGetSourceFile,
                 SymGetSourceFileChecksum,
                 SymGetSourceFileFromToken,
                 SymGetSourceFileToken,
                 SymGetSourceVarFromToken,
                 SymGetSymbolFile,
                 SymGetSymFromAddr,
                 SymGetSymFromName,
                 SymGetSymNext,
                 SymGetSymPrev,
                 SymGetTypeFromName,
                 SymGetTypeInfo,
                 SymGetTypeInfoEx,
                 SymInitialize,
                 SymLoadModule,
                 SymLoadModuleEx,
                 SymMatchFileName,
                 SymMatchString,
                 SymNext,
                 SymPrev,
                 SymQueryInlineTrace,
                 SymRefreshModuleList,
                 SymRegisterCallback,
                 SymRegisterFunctionEntryCallback,
                 SymSearch,
                 SymSetContext,
                 SymSetExtendedOption,
                 SymSetHomeDirectory,
                 SymSetOptions,
                 SymSetParentWindow,
                 SymSetScopeFromAddr,
                 SymSetScopeFromIndex,
                 SymSetScopeFromInlineContext,
                 SymSetSearchPath,
                 SymSrvDeltaName,
                 SymSrvGetFileIndexes,
                 SymSrvGetFileIndexInfo,
                 SymSrvGetFileIndexString,
                 SymSrvGetSupplement,
                 SymSrvIsStore,
                 SymSrvStoreFile,
                 SymSrvStoreSupplement,
                 SymUnDName,
                 SymUnloadModule,
                 UnDecorateSymbolName)
    };

    class WindowsKernelApi{
      DynamicLoader kernelLib{VALKYRIE_KERNEL_LIBRARY};
    public:
      VK_foreach(VK_bind_front(VK_load_function, kernelLib),


      /* Processes and Threads */

                 CreateProcess,
                 CreateProcessAsUser,
                 CreateRemoteThread,
                 CreateRemoteThreadEx,
                 CreateThread,
                 DeleteProcThreadAttributeList,
                 ExitProcess,
                 ExitThread,
                 FlushInstructionCache,
                 FlushProcessWriteBuffers,
                 GetCurrentProcess,
                 GetCurrentProcessId,
                 GetCurrentProcessorNumber,
                 GetCurrentProcessorNumberEx,
                 GetCurrentProcessToken,
                 GetCurrentThread,
                 GetCurrentThreadEffectiveToken,
                 GetCurrentThreadId,
                 GetCurrentThreadStackLimits,
                 GetExitCodeProcess,
                 GetExitCodeThread,
                 GetPriorityClass,
                 GetProcessHandleCount,
                 GetProcessId,
                 GetProcessIdOfThread,
                 GetProcessInformation,
                 GetProcessMitigationPolicy,
                 GetProcessPriorityBoost,
                 GetProcessShutdownParameters,
                 GetProcessTimes,
                 GetProcessVersion,
                 GetStartupInfo,
                 GetSystemTimes,
                 GetThreadContext,
                 GetThreadDescription,
                 GetThreadId,
                 GetThreadIdealProcessorEx,
                 GetThreadInformation,
                 GetThreadIOPendingFlag,
                 GetThreadPriority,
                 GetThreadPriorityBoost,
                 GetThreadTimes,
                 InitializeProcThreadAttributeList,
                 IsProcessCritical,
                 IsProcessorFeaturePresent,
                 OpenProcess,
                 OpenProcessToken,
                 OpenThread,
                 OpenThreadToken,
                 ProcessIdToSessionId,
                 QueryProcessAffinityUpdateMode,
                 QueryProtectedPolicy,
                 QueueUserAPC,
                 ResumeThread,
                 SetPriorityClass,
                 SetProcessAffinityUpdateMode,
                 SetProcessInformation,
                 SetProcessMitigationPolicy,
                 SetProcessPriorityBoost,
                 SetProcessShutdownParameters,
                 SetProtectedPolicy,
                 SetThreadContext,
                 SetThreadDescription,
                 SetThreadIdealProcessor,
                 SetThreadIdealProcessorEx,
                 SetThreadInformation,
                 SetThreadPriority,
                 SetThreadPriorityBoost,
                 SetThreadStackGuarantee,
                 SetThreadToken,
                 SuspendThread,
                 SwitchToThread,
                 TerminateProcess,
                 TerminateThread,
                 TlsAlloc,
                 TlsFree,
                 TlsGetValue,
                 TlsSetValue,
                 UpdateProcThreadAttribute)


      VK_foreach(VK_bind_front(VK_load_function, kernelLib),


      /* Memory */

                 AllocateUserPhysicalPages,
                 CreateFileMapping2,
                 CreateFileMapping,
                 CreateMemoryResourceNotification,
                 DiscardVirtualMemory,
                 FlushViewOfFile,
                 FreeUserPhysicalPages,
                 GetLargePageMinimum,
                 GetMemoryErrorHandlingCapabilities,
                 GetSystemFileCacheSize,
                 GetWriteWatch,
                 MapUserPhysicalPages,
                 MapViewOfFile,
                 MapViewOfFile2,
                 MapViewOfFile3,
                 MapViewOfFileEx,
                 MapViewOfFileNuma2,
                 OfferVirtualMemory,
                 OpenFileMappingFromApp,
                 OpenFileMapping,
                 PrefetchVirtualMemory,
                 QueryMemoryResourceNotification,
                 QueryVirtualMemoryInformation,
                 ReclaimVirtualMemory,
                 RegisterBadMemoryNotification,
                 ResetWriteWatch,
                 SetProcessValidCallTargets,
                 SetSystemFileCacheSize,
                 UnmapViewOfFile,
                 UnmapViewOfFile2,
                 UnmapViewOfFileEx,
                 UnregisterBadMemoryNotification,
                 VirtualAlloc,
                 VirtualAlloc2,
                 VirtualAllocEx,
                 VirtualAllocExNuma,
                 VirtualFree,
                 VirtualFreeEx,
                 VirtualLock,
                 VirtualProtect,
                 VirtualProtectEx,
                 VirtualQuery,
                 VirtualQueryEx,
                 VirtualUnlock)



      /* Process status */
      VK_foreach(VK_bind_front(VK_load_function, kernelLib),

                 EmptyWorkingSet,
                 EnumDeviceDrivers,
                 EnumPageFiles,
                 EnumProcesses,
                 EnumProcessModules,
                 EnumProcessModulesEx,
                 GetDeviceDriverBaseName,
                 GetDeviceDriverFileName,
                 GetMappedFileName,
                 GetModuleBaseName,
                 GetModuleFileName,
                 GetModuleInformation,
                 GetPerformanceInfo,
                 GetProcessImageFileName,
                 GetProcessMemoryInfo,
                 GetWsChanges,
                 GetWsChangesEx,
                 InitializeProcessForWsWatch,
                 QueryWorkingSet,
                 QueryWorkingSetEx)



      /* Debugging */

      VK_foreach(VK_bind_front(VK_load_function, kernelLib),
                 CheckRemoteDebuggerPresent,
                 ContinueDebugEvent,
                 DebugActiveProcess,
                 DebugActiveProcessStop,
                 DebugBreak,
                 IsDebuggerPresent,
                 OutputDebugString,
                 WaitForDebugEvent,
                 WaitForDebugEventEx)



      /* Handles */

      VK_foreach(VK_bind_front(VK_load_function, kernelLib),
                     CloseHandle,
                     CompareObjectHandles,
                     DuplicateHandle,
                     GetHandleInformation,
                     SetHandleInformation)


      /* Files */

      VK_foreach(VK_bind_front(VK_load_function, kernelLib),
                     AreFileApisANSI,
                     CompareFileTime,
                     CreateDirectory,
                     CreateFile,
                     CreateFile2,
                     DeleteFile,
                     DeleteVolumeMountPoint,
                     FileTimeToLocalFileTime,
                     FindClose,
                     FindCloseChangeNotification,
                     FindFirstChangeNotification,
                     FindFirstFile,
                     FindFirstFileEx,
                     FindFirstStreamW,
                     FindFirstVolume,
                     FindNextChangeNotification,
                     FindNextFile,
                     FindNextFileNameW,
                     FindNextStreamW,
                     FindNextVolume,
                     FindVolumeClose,
                     FlushFileBuffers,
                     GetCompressedFileSize,
                     GetDiskFreeSpace,
                     GetDiskFreeSpaceEx,
                     GetDriveType,
                     GetFileAttributes,
                     GetFileAttributesEx,
                     GetFileInformationByHandle,
                     GetFileSize,
                     GetFileSizeEx,
                     GetFileTime,
                     GetFileType,
                     GetFinalPathNameByHandle,
                     GetFullPathName,
                     GetLogicalDrives,
                     GetLogicalDriveStrings,
                     GetLongPathName,
                     GetShortPathName,
                     GetTempFileName,
                     GetTempPath,
                     GetVolumeInformation,
                     GetVolumeInformationByHandleW,
                     GetVolumeNameForVolumeMountPoint,
                     GetVolumePathNamesForVolumeNameW,
                     GetVolumePathName,
                     LocalFileTimeToFileTime,
                     LockFile,
                     LockFileEx,
                     ReadFile,
                     ReadFileEx,
                     ReadFileScatter,
                     RemoveDirectory,
                     SetEndOfFile,
                     SetFileApisToANSI,
                     SetFileApisToOEM,
                     SetFileAttributes,
                     SetFileInformationByHandle,
                     SetFileIoOverlappedRange,
                     SetFilePointer,
                     SetFilePointerEx,
                     SetFileTime,
                     SetFileValidData,
                     UnlockFile,
                     UnlockFileEx,
                     WriteFile,
                     WriteFileEx,
                     WriteFileGather)
    };
  }

  extern const DebugApi         debugApi;
  extern const WindowsKernelApi kernelApi;
}

#endif//VALKYRIE_SRC_WIN32_FUNCTIONS_HPP
