//
// Created by Maxwell on 2020-12-02.
//

#include <valkyrie/Core/Utility/FlatMap.hpp>

#include "DXGI.hpp"

#include <array>

namespace valkyrie::GUI::Internal::DXGI{
  namespace {

    template <std::default_initializable T, size_t N>
    requires(std::is_trivially_destructible_v<T>)
    struct alignas(16) StaticArray{

      using value_type = T;
      using allocator_type = void;
      using size_type = u32;
      using difference_type = i32;

      using iterator = T*;
      using const_iterator = const T*;
      using reverse_iterator = std::reverse_iterator<iterator>;
      using const_reverse_iterator = std::reverse_iterator<const_iterator>;

      using reference = T&;
      using const_reference = const T&;
      using pointer = iterator;
      using const_pointer = const_iterator;

      constexpr StaticArray() = default;
      template <std::convertible_to<T> ...Args>
      constexpr StaticArray(Args&& ...args) noexcept 
          : count(sizeof...(Args)), values{ std::forward<Args>(args)... }{}
      constexpr StaticArray(std::initializer_list<T> list) noexcept
          : count(list.size()){
        std::copy(list.begin(), list.end(), values);
      }

      constexpr bool empty() const noexcept {
        return count == 0;
      }
      constexpr size_type size() const noexcept {
        return count;
      }
      constexpr static size_type max_size() noexcept {
        return (u32)N;
      }


      constexpr iterator       begin()        noexcept {
        return values;
      }
      constexpr const_iterator begin()  const noexcept {
        return values;
      }
      constexpr const_iterator cbegin() const noexcept {
        return values;
      }

      constexpr iterator       end()        noexcept {
        return begin() + count;
      }
      constexpr const_iterator end()  const noexcept {
        return begin() + count;
      }
      constexpr const_iterator cend() const noexcept {
        return begin() + count;
      }

      u32 count = 0;
      T values[N]{};
    };

    using MappingMapEntry = Core::FlatMapEntry<DXGI_FORMAT, FormatMapping>;
    using FamilyMapEntry  = Core::FlatMapEntry<DXGI_FORMAT, FormatFamily>;

    using MappingMapContainer = StaticArray<MappingMapEntry, 106>;
    using FamilyMapContainer  = StaticArray<FamilyMapEntry,  40>;

    using MappingMap = Core::FlatMap<Format, FormatMapping, MappingMapContainer>;
    using FamilyMap  = Core::FlatMap<Format, FormatFamily,  FamilyMapContainer>;

    static_assert(sizeof(MappingMap) == 4256);
    static_assert(sizeof(FamilyMap) == 976);

    inline constexpr FormatMapping invalidMapping{};
    inline constexpr FormatFamily  invalidFamily{};

#pragma region Mappings
    inline constexpr MappingMap mappings{
        Core::guaranteeUnique,
        /*std::initializer_list<MappingMapEntry>*/{
            { DXGI_FORMAT_R32G32B32A32_TYPELESS,
                { Format::R32G32B32A32UInt,
                    Format::Undefined,
                    Format::R32G32B32A32UInt }},
            { DXGI_FORMAT_R32G32B32A32_FLOAT,
                { Format::R32G32B32A32SFloat,
                    Format::Undefined,
                    Format::R32G32B32A32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R32G32B32A32_UINT,
                {  Format::R32G32B32A32UInt,
                    Format::Undefined,
                    Format::R32G32B32A32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R32G32B32A32_SINT,
                {  Format::R32G32B32A32SInt,
                    Format::Undefined,
                    Format::R32G32B32A32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R32G32B32_TYPELESS,
                {  Format::R32G32B32UInt,
                    Format::Undefined,
                    Format::R32G32B32UInt  }},
            {  DXGI_FORMAT_R32G32B32_FLOAT,
                {  Format::R32G32B32SFloat,
                    Format::Undefined,
                    Format::R32G32B32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R32G32B32_UINT,
                {  Format::R32G32B32UInt,
                    Format::Undefined,
                    Format::R32G32B32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R32G32B32_SINT,
                {  Format::R32G32B32SInt,
                    Format::Undefined,
                    Format::R32G32B32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R16G16B16A16_TYPELESS,
                {  Format::R16G16B16A16UNorm,
                    Format::Undefined,
                    Format::R16G16B16A16UInt  }},
            {  DXGI_FORMAT_R16G16B16A16_FLOAT,
                {  Format::R16G16B16A16SFloat,
                    Format::Undefined,
                    Format::R16G16B16A16UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R16G16B16A16_UNORM,
                {  Format::R16G16B16A16UNorm,
                    Format::Undefined,
                    Format::R16G16B16A16UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R16G16B16A16_UINT,
                {  Format::R16G16B16A16UInt,
                    Format::Undefined,
                    Format::R16G16B16A16UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R16G16B16A16_SNORM,
                {  Format::R16G16B16A16SNorm,
                    Format::Undefined,
                    Format::R16G16B16A16UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R16G16B16A16_SINT,
                {  Format::R16G16B16A16SInt,
                    Format::Undefined,
                    Format::R16G16B16A16UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R32G32_TYPELESS,
                {  Format::R32G32UInt,
                    Format::Undefined,
                    Format::R32G32UInt  }},
            {  DXGI_FORMAT_R32G32_FLOAT,
                {  Format::R32G32SFloat,
                    Format::Undefined,
                    Format::R32G32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R32G32_UINT,
                {  Format::R32G32UInt,
                    Format::Undefined,
                    Format::R32G32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R32G32_SINT,
                {  Format::R32G32SInt,
                    Format::Undefined,
                    Format::R32G32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R32G8X24_TYPELESS,
                {  Format::Undefined,
                    Format::D32SFloatS8UInt,
                    Format::Undefined  }},
            {  DXGI_FORMAT_D32_FLOAT_S8X24_UINT,
                {  Format::Undefined,
                    Format::D32SFloatS8UInt,
                    Format::Undefined,
                    {},
                    ImageAspect::Depth | ImageAspect::Stencil  }},
            {  DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS,
                {  Format::Undefined,
                    Format::D32SFloatS8UInt,
                    Format::Undefined,
                    {},
                    ImageAspect::Depth  }},
            {  DXGI_FORMAT_X32_TYPELESS_G8X24_UINT,
                {  Format::Undefined,
                    Format::D32SFloatS8UInt,
                    Format::Undefined,
                    {},
                    ImageAspect::Stencil  }},
            {  DXGI_FORMAT_R10G10B10A2_TYPELESS,
                {  Format::A2B10G10R10UNormPack32,
                    Format::Undefined,
                    Format::A2B10G10R10UIntPack32  }},
            {  DXGI_FORMAT_R10G10B10A2_UNORM,
                {  Format::A2B10G10R10UNormPack32,
                    Format::Undefined,
                    Format::A2B10G10R10UIntPack32,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R10G10B10A2_UINT,
                {  Format::A2B10G10R10UIntPack32,
                    Format::Undefined,
                    Format::A2B10G10R10UIntPack32,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R11G11B10_FLOAT,
                {  Format::B10G11R11UFloatPack32,
                    Format::Undefined,
                    Format::R32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R8G8B8A8_TYPELESS,
                {  Format::R8G8B8A8UNorm,
                    Format::Undefined,
                    Format::R8G8B8A8UInt  }},
            {  DXGI_FORMAT_R8G8B8A8_UNORM,
                {  Format::R8G8B8A8UNorm,
                    Format::Undefined,
                    Format::R8G8B8A8UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,
                {  Format::R8G8B8A8SRGB,
                    Format::Undefined,
                    Format::R8G8B8A8UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R8G8B8A8_UINT,
                {  Format::R8G8B8A8UInt,
                    Format::Undefined,
                    Format::R8G8B8A8UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R8G8B8A8_SNORM,
                {  Format::R8G8B8A8SNorm,
                    Format::Undefined,
                    Format::R8G8B8A8UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R8G8B8A8_SINT,
                {  Format::R8G8B8A8SInt,
                    Format::Undefined,
                    Format::R8G8B8A8UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R16G16_TYPELESS,
                {  Format::R16G16UNorm,
                    Format::Undefined,
                    Format::R16G16UInt  }},
            {  DXGI_FORMAT_R16G16_FLOAT,
                {  Format::R16G16SFloat,
                    Format::Undefined,
                    Format::R16G16UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R16G16_UNORM,
                {  Format::R16G16UNorm,
                    Format::Undefined,
                    Format::R16G16UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R16G16_UINT,
                {  Format::R16G16UInt,
                    Format::Undefined,
                    Format::R16G16UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R16G16_SNORM,
                {  Format::R16G16SNorm,
                    Format::Undefined,
                    Format::R16G16UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R16G16_SINT,
                {  Format::R16G16SInt,
                    Format::Undefined,
                    Format::R16G16UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R32_TYPELESS,
                {  Format::R32UInt,
                    Format::D32SFloat,
                    Format::R32UInt  }},
            {  DXGI_FORMAT_D32_FLOAT,
                {  Format::Undefined,
                    Format::D32SFloat,
                    Format::Undefined,
                    {},
                    ImageAspect::Depth  }},
            {  DXGI_FORMAT_R32_FLOAT,
                {  Format::R32SFloat,
                    Format::D32SFloat,
                    Format::R32UInt,
                    ImageAspect::Color,
                    ImageAspect::Depth  }},
            {  DXGI_FORMAT_R32_UINT,
                {  Format::R32UInt,
                    Format::Undefined,
                    Format::R32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R32_SINT,
                {  Format::R32SInt,
                    Format::Undefined,
                    Format::R32UInt,
                    ImageAspect::Color  }},
            {  DXGI_FORMAT_R24G8_TYPELESS,
                {  Format::Undefined,
                    Format::D24UNormS8UInt,
                    Format::Undefined  }},
            ////////////////////////
          {
            DXGI_FORMAT_D24_UNORM_S8_UINT,
            FormatMapping{ Format::Undefined,
            Format::D24UNormS8UInt,
            Format::Undefined,
            {},
            ImageAspect::Depth | ImageAspect::Stencil }},
          {  DXGI_FORMAT_R24_UNORM_X8_TYPELESS,
            {  Format::Undefined,
            Format::D24UNormS8UInt,
            Format::Undefined,
            {},
            ImageAspect::Depth  }},
          {  DXGI_FORMAT_X24_TYPELESS_G8_UINT,
            {  Format::Undefined,
            Format::D24UNormS8UInt,
            Format::Undefined,
            {},
            ImageAspect::Stencil  }},
          {  DXGI_FORMAT_R8G8_TYPELESS,
            {  Format::R8G8UNorm,
            Format::Undefined,
            Format::R8G8UInt  }},
          {  DXGI_FORMAT_R8G8_UNORM,
            {  Format::R8G8UNorm,
            Format::Undefined,
            Format::R8G8UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_R8G8_UINT,
            {  Format::R8G8UInt,
            Format::Undefined,
            Format::R8G8UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_R8G8_SNORM,
            {  Format::R8G8SNorm,
            Format::Undefined,
            Format::R8G8UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_R8G8_SINT,
            {  Format::R8G8SInt,
            Format::Undefined,
            Format::R8G8UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_R16_TYPELESS,
            {  Format::R16UNorm,
            Format::D16UNorm,
            Format::R16UInt  }},
          {  DXGI_FORMAT_R16_FLOAT,
            {  Format::R16SFloat,
            Format::D16UNorm,
            Format::R16UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_D16_UNORM,
            {  Format::Undefined,
            Format::D16UNorm,
            Format::Undefined,
            {},
            ImageAspect::Depth  }},
          {  DXGI_FORMAT_R16_UNORM,
            {  Format::R16UNorm,
            Format::D16UNorm,
            Format::R16UInt,
            ImageAspect::Color,
            ImageAspect::Depth  }},
          {  DXGI_FORMAT_R16_UINT,
            {  Format::R16UInt,
            Format::Undefined,
            Format::R16UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_R16_SNORM,
            {  Format::R16SNorm,
            Format::Undefined,
            Format::R16UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_R16_SINT,
            {  Format::R16SInt,
            Format::Undefined,
            Format::R16UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_R8_TYPELESS,
            {  Format::R8UNorm,
            Format::Undefined,
            Format::R8UInt  }},
          {  DXGI_FORMAT_R8_UNORM,
            {  Format::R8UNorm,
            Format::Undefined,
            Format::R8UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_R8_UINT,
            {  Format::R8UInt,
            Format::Undefined,
            Format::R8UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_R8_SNORM,
            {  Format::R8SNorm,
            Format::Undefined,
            Format::R8UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_R8_SINT,
            {  Format::R8SInt,
            Format::Undefined,
            Format::R8UInt,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_A8_UNORM,
            {  Format::R8UNorm,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color,
            {},
            { Swizzle::Zero, Swizzle::Zero,
              Swizzle::Zero, Swizzle::R  }}},
          {  DXGI_FORMAT_R9G9B9E5_SHAREDEXP,
            {  Format::E5B9G9R9UFloatPack32,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_R8G8_B8G8_UNORM,
            {  Format::B8G8R8G8_422UNorm,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color,
            {},
            { Swizzle::B, Swizzle::G,
              Swizzle::R, Swizzle::One  }}},
          {  DXGI_FORMAT_G8R8_G8B8_UNORM,
            {  Format::G8B8G8R8_422UNorm,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color,
            {},
            { Swizzle::B, Swizzle::G,
              Swizzle::R, Swizzle::One  }}},
          {  DXGI_FORMAT_BC1_TYPELESS,
            {  Format::Bc1RGBAUNormBlock,
            Format::Undefined,
            Format::Undefined  }},
          {  DXGI_FORMAT_BC1_UNORM,
            {  Format::Bc1RGBAUNormBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC1_UNORM_SRGB,
            {  Format::Bc1RGBASRGBBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC2_TYPELESS,
            {  Format::Bc2UNormBlock,
            Format::Undefined,
            Format::Undefined  }},
          {  DXGI_FORMAT_BC2_UNORM,
            {  Format::Bc2UNormBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC2_UNORM_SRGB,
            {  Format::Bc2SRGBBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC3_TYPELESS,
            {  Format::Bc3UNormBlock,
            Format::Undefined,
            Format::Undefined  }},
          {  DXGI_FORMAT_BC3_UNORM,
            {  Format::Bc3UNormBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC3_UNORM_SRGB,
            {  Format::Bc3SRGBBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC4_TYPELESS,
            {  Format::Bc4UNormBlock,
            Format::Undefined,
            Format::Undefined  }},
          {  DXGI_FORMAT_BC4_UNORM,
            {  Format::Bc4UNormBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC4_SNORM,
            {  Format::Bc4SNormBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC5_TYPELESS,
            {  Format::Bc5UNormBlock,
            Format::Undefined,
            Format::Undefined  }},
          {  DXGI_FORMAT_BC5_UNORM,
            {  Format::Bc5UNormBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC5_SNORM,
            {  Format::Bc5SNormBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_B5G6R5_UNORM,
            {  Format::R5G6B5UNormPack16,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_B5G5R5A1_UNORM,
            {  Format::A1R5G5B5UNormPack16,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_B8G8R8A8_UNORM,
            {  Format::B8G8R8A8UNorm,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_B8G8R8X8_UNORM,
            {  Format::B8G8R8A8UNorm,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color,
            {},
            { Swizzle::R, Swizzle::G,
              Swizzle::B, Swizzle::One  }}},
          {  DXGI_FORMAT_B8G8R8A8_TYPELESS,
            {  Format::B8G8R8A8UNorm,
            Format::Undefined,
            Format::Undefined  }},
          {  DXGI_FORMAT_B8G8R8A8_UNORM_SRGB,
            {  Format::B8G8R8A8SRGB,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_B8G8R8X8_TYPELESS,
            {  Format::B8G8R8A8UNorm,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_B8G8R8X8_UNORM_SRGB,
            {  Format::B8G8R8A8SRGB,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color,
            {},
            { Swizzle::R, Swizzle::G,
              Swizzle::B, Swizzle::One  }}},
          {  DXGI_FORMAT_BC6H_TYPELESS,
            {  Format::Bc6hUFloatBlock,
            Format::Undefined,
            Format::Undefined  }},
          {  DXGI_FORMAT_BC6H_UF16,
            {  Format::Bc6hUFloatBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC6H_SF16,
            {  Format::Bc6hSFloatBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC7_TYPELESS,
            {  Format::Bc7UNormBlock,
            Format::Undefined,
            Format::Undefined  }},
          {  DXGI_FORMAT_BC7_UNORM,
            {  Format::Bc7UNormBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_BC7_UNORM_SRGB,
            {  Format::Bc7SRGBBlock,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }},
          {  DXGI_FORMAT_B4G4R4A4_UNORM,
            {  Format::A4R4G4B4UNormPack16EXT,
            Format::Undefined,
            Format::Undefined,
            ImageAspect::Color  }}
        }};
#pragma endregion Mappings
#pragma region Families
    inline constexpr FamilyMap families{
        Core::guaranteeUnique, {
          {  DXGI_FORMAT_R32G32B32A32_TYPELESS,
            {  Format::R32G32B32A32UInt,
            Format::R32G32B32A32SInt,
            Format::R32G32B32A32SFloat  }},
          {  DXGI_FORMAT_R32G32B32_TYPELESS,
            {  Format::R32G32B32UInt,
            Format::R32G32B32SInt,
            Format::R32G32B32SFloat  }},
          {  DXGI_FORMAT_R16G16B16A16_TYPELESS,
            {  Format::R16G16B16A16UNorm,
            Format::R16G16B16A16SNorm,
            Format::R16G16B16A16UInt,
            Format::R16G16B16A16SInt,
            Format::R16G16B16A16SFloat  }},
          {  DXGI_FORMAT_R32G32_TYPELESS,
            {  Format::R32G32UInt,
            Format::R32G32SInt,
            Format::R32G32SFloat  }},
          {  DXGI_FORMAT_R10G10B10A2_TYPELESS,
            {  Format::A2B10G10R10UNormPack32,
            Format::A2B10G10R10UIntPack32  }},
          {  DXGI_FORMAT_R8G8B8A8_TYPELESS,
            {  Format::R8G8B8A8UNorm,
            Format::R8G8B8A8SNorm,
            Format::R8G8B8A8SRGB,
            Format::R8G8B8A8UInt,
            Format::R8G8B8A8SInt  }},
          {  DXGI_FORMAT_R8G8B8A8_UNORM,
            {  Format::R8G8B8A8UNorm,
            Format::R8G8B8A8SRGB  }},
          {  DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,
            {  Format::R8G8B8A8UNorm,
            Format::R8G8B8A8SRGB  }},
          {  DXGI_FORMAT_R16G16_TYPELESS,
            {  Format::R16G16UNorm,
            Format::R16G16SNorm,
            Format::R16G16UInt,
            Format::R16G16SInt,
            Format::R16G16SFloat  }},
          {  DXGI_FORMAT_R32_TYPELESS,
            {  Format::R32UInt,
            Format::R32SInt,
            Format::R32SFloat  }},
          {  DXGI_FORMAT_R8G8_TYPELESS,
            {  Format::R8G8UNorm,
            Format::R8G8SNorm,
            Format::R8G8UInt,
            Format::R8G8SInt  }},
          {  DXGI_FORMAT_R16_TYPELESS,
            {  Format::R16UNorm,
            Format::R16SNorm,
            Format::R16UInt,
            Format::R16SInt,
            Format::R16SFloat  }},
          {  DXGI_FORMAT_R8_TYPELESS,
            {  Format::R8UNorm,
            Format::R8SNorm,
            Format::R8UInt,
            Format::R8SInt  }},
          {  DXGI_FORMAT_BC1_TYPELESS,
            {  Format::Bc1RGBAUNormBlock,
            Format::Bc1RGBASRGBBlock  }},
          {  DXGI_FORMAT_BC1_UNORM,
            {  Format::Bc1RGBAUNormBlock,
            Format::Bc1RGBASRGBBlock  }},
          {  DXGI_FORMAT_BC1_UNORM_SRGB,
            {  Format::Bc1RGBAUNormBlock,
            Format::Bc1RGBASRGBBlock  }},
          {  DXGI_FORMAT_BC2_TYPELESS,
            {  Format::Bc2UNormBlock,
            Format::Bc2SRGBBlock  }},
          {  DXGI_FORMAT_BC2_UNORM,
            {  Format::Bc2UNormBlock,
            Format::Bc2SRGBBlock  }},
          {  DXGI_FORMAT_BC2_UNORM_SRGB,
            {  Format::Bc2UNormBlock,
            Format::Bc2SRGBBlock  }},
          {  DXGI_FORMAT_BC3_TYPELESS,
            {  Format::Bc3UNormBlock,
            Format::Bc3SRGBBlock  }},
          {  DXGI_FORMAT_BC3_UNORM,
            {  Format::Bc3UNormBlock,
            Format::Bc3SRGBBlock  }},
          {  DXGI_FORMAT_BC3_UNORM_SRGB,
            {  Format::Bc3UNormBlock,
            Format::Bc3SRGBBlock  }},
          {  DXGI_FORMAT_BC4_TYPELESS,
            {  Format::Bc4UNormBlock,
            Format::Bc4SNormBlock  }},
          {  DXGI_FORMAT_BC5_TYPELESS,
            {  Format::Bc5UNormBlock,
            Format::Bc5SNormBlock  }},
          {  DXGI_FORMAT_B8G8R8A8_UNORM,
            {  Format::B8G8R8A8UNorm,
            Format::B8G8R8A8SRGB  }},
          {  DXGI_FORMAT_B8G8R8X8_UNORM,
            {  Format::B8G8R8A8UNorm,
            Format::B8G8R8A8SRGB  }},
          {  DXGI_FORMAT_B8G8R8A8_TYPELESS,
            {  Format::B8G8R8A8UNorm,
            Format::B8G8R8A8SRGB  }},
          {  DXGI_FORMAT_B8G8R8A8_UNORM_SRGB,
            {  Format::B8G8R8A8UNorm,
            Format::B8G8R8A8SRGB  }},
          {  DXGI_FORMAT_B8G8R8X8_TYPELESS,
            {  Format::B8G8R8A8UNorm,
            Format::B8G8R8A8SRGB  }},
          {  DXGI_FORMAT_B8G8R8X8_UNORM_SRGB,
            {  Format::B8G8R8A8UNorm,
            Format::B8G8R8A8SRGB  }},
          {  DXGI_FORMAT_BC6H_TYPELESS,
            {  Format::Bc6hUFloatBlock,
            Format::Bc6hSFloatBlock  }},
          {  DXGI_FORMAT_BC7_TYPELESS,
            {  Format::Bc7UNormBlock,
            Format::Bc7SRGBBlock  }},
          {  DXGI_FORMAT_BC7_UNORM,
            {  Format::Bc7UNormBlock,
            Format::Bc7SRGBBlock  }},
          {  DXGI_FORMAT_BC7_UNORM_SRGB,
            {  Format::Bc7UNormBlock,
            Format::Bc7SRGBBlock  }}
    }};
#pragma endregion Families
  }

  FormatInfo getFormatInfo(DXGI_FORMAT Format, FormatMode Mode) noexcept{

    auto&& searchResult = mappings.find(Format);

    const FormatMapping& mapping = searchResult == mappings.end() ? invalidMapping : searchResult->value;

    switch (Mode) {
      case FormatMode::Any:
        return mapping.colorCompatible != Format::Undefined
                   ? FormatInfo{ mapping.colorCompatible, mapping.aspectColor, mapping.swizzle }
                   : FormatInfo{ mapping.depthCompatible, mapping.aspectDepth };
      case FormatMode::Color:
        return { mapping.colorCompatible, mapping.aspectColor, mapping.swizzle };
      case FormatMode::Depth:
        return { mapping.depthCompatible, mapping.aspectDepth };
      case FormatMode::Raw:
        return { mapping.bitCompatible,   mapping.aspectColor };
      VK_no_default;
    }
  }
  FormatInfo getPackedFormatInfo(DXGI_FORMAT Format, FormatMode Mode) noexcept{
    return getFormatInfo(Format, Mode);
  }
  FormatFamily getFormatFamily(DXGI_FORMAT Format, FormatMode Mode) noexcept{
    auto&& searchResult = families.find(Format);
    return searchResult == families.end() ? FormatFamily{} : searchResult->value;
  }
}
