//
// Created by maxwe on 2021-04-07.
//

#ifndef VALKYRIE_JSON_VALIDATION_H
#define VALKYRIE_JSON_VALIDATION_H

#include "core.h"


JSON_BEGIN_C_NAMESPACE


typedef enum json_validation_status{
  JSON_VALIDATION_SUCCESS,
  JSON_VALIDATION_ERROR_MULTIPLE_OF,
  JSON_VALIDATION_ERROR_MAXIMUM,
  JSON_VALIDATION_ERROR_EXCLUSIVE_MAXIMUM,
  JSON_VALIDATION_ERROR_MINIMUM,
  JSON_VALIDATION_ERROR_EXCLUSIVE_MINIMUM,

  JSON_VALIDATION_ERROR_MAX_LENGTH,
  JSON_VALIDATION_ERROR_MIN_LENGTH,
  JSON_VALIDATION_ERROR_PATTERN,

  JSON_VALIDATION_ERROR_MAX_ITEMS,
  JSON_VALIDATION_ERROR_MIN_ITEMS,
  JSON_VALIDATION_ERROR_UNIQUE_ITEMS,
  JSON_VALIDATION_ERROR_ADDITIONAL_ITEMS,

  JSON_VALIDATION_ERROR_MAX_PROPERTIES,
  JSON_VALIDATION_ERROR_MIN_PROPERTIES,
  JSON_VALIDATION_ERROR_REQUIRED,
  JSON_VALIDATION_ERROR_ADDITIONAL_PROPERTIES,
  JSON_VALIDATION_ERROR_PATTERN_PROPERTIES,
  JSON_VALIDATION_ERROR_DEPENDENCIES,

  JSON_VALIDATION_ERROR_ENUM,
  JSON_VALIDATION_ERROR_TYPE,

  JSON_VALIDATION_ERROR_ONE_OF,
  JSON_VALIDATION_ERROR_ONE_OF_MATCH,
  JSON_VALIDATION_ERROR_ALL_OF,
  JSON_VALIDATION_ERROR_ANY_OF,
  JSON_VALIDATION_ERROR_NOT
} json_validation_status_t;







JSON_END_C_NAMESPACE

#endif//VALKYRIE_JSON_VALIDATION_H
